# Exact-release, unchanged first-party RTX adapter. No NVIDIA runtime is bundled.
set(_pinned_adapter_sha "bffcf3ba0586d8ed6ffde6574689157cb291163c010c5bff4b96052710060d74")
set(_pinned_runtime_sha "9a80575f247190c05fe80eac0c4baa1d0d4d932348f26808310b5ec4bf9eeb4b")
set(_pinned_abi_sha "89bf5415feef0aa3d248bfd5f3d68feeaad37daa9f0dafa1ac9ab9f80b8563b2")
get_filename_component(_pinned_root "${SUNSHINE_PINNED_RELEASE_ADAPTER_DIR}" ABSOLUTE)
set(RTX_VIDEO_ADAPTER_DLL "${_pinned_root}/foundation_rtx_video_adapter.dll")
if (NOT EXISTS "${RTX_VIDEO_ADAPTER_DLL}")
  message(FATAL_ERROR "The pinned first-party adapter is missing; RTX HDR will not be silently disabled")
endif ()
file(SHA256 "${RTX_VIDEO_ADAPTER_DLL}" _actual_adapter)
# Git on Windows checks text out as CRLF. Only canonicalize line endings;
# any other header change must still reject this prebuilt C ABI adapter.
file(READ "${CMAKE_SOURCE_DIR}/src/platform/windows/hdr_enhanced/nvidia_rtx_video/adapter_abi.h" _abi_text)
string(REPLACE "\r\n" "\n" _abi_canonical "${_abi_text}")
string(SHA256 _actual_abi "${_abi_canonical}")
if (NOT _actual_adapter STREQUAL _pinned_adapter_sha OR NOT _actual_abi STREQUAL _pinned_abi_sha)
  message(FATAL_ERROR "Pinned RTX adapter/ABI mismatch: adapter=${_actual_adapter}; canonical ABI=${_actual_abi}")
endif ()
set(RTX_VIDEO_TRUST_INCLUDE "${CMAKE_BINARY_DIR}/generated/rtx_video")
set(RTX_VIDEO_TRUST_HEADER "${RTX_VIDEO_TRUST_INCLUDE}/rtx_video_trust.h")
file(MAKE_DIRECTORY "${RTX_VIDEO_TRUST_INCLUDE}")
file(WRITE "${RTX_VIDEO_TRUST_HEADER}"
  "#pragma once\n#define SUNSHINE_RTX_VIDEO_ADAPTER_SHA256 \"${_pinned_adapter_sha}\"\n#define SUNSHINE_RTX_VIDEO_RUNTIME_SHA256 \"${_pinned_runtime_sha}\"\n")
add_custom_target(sunshine_rtx_video_adapter DEPENDS "${RTX_VIDEO_ADAPTER_DLL}" "${RTX_VIDEO_TRUST_HEADER}")
set(SUNSHINE_RTX_HDR_AVAILABLE TRUE CACHE INTERNAL "RTX HDR adapter is configured" FORCE)
message(STATUS "RTX HDR enabled: exact-release adapter and canonical host ABI verified; runtime verification unchanged")
